### ISSUE TITLE
\footnote{\footcite[vgl.][10]{source}} zu \cite[vgl.][10]{source} abändern

### ISSUE THREAD

**Issue by thunermay** [FHDWPB/latex-thesis-template#16]
In der Vorlage wird implizit gesagt, dass man sobald man ein vergleichendes Zitat benutzen möchte, man den `\footnote` und `\cite` getrennt benutzen müsste und nur bei wörtlichen Zitaten `\footcite` benutzen muss. Stand jetzt als ich es getestet habe ist es genauso möglich ein vergleichendes Zitat ausschließlich mit `\footcite` zu tun. Das spart deutlich am Aufwand und verringert die Komplexität.

**Comment by mfueller** [comment]
Danke für den Hinweis.
Wenn ich es richtig verstehe und wie ich es auch gerade getestet habe, meinst du folgende Zeile:

```latex
Ein vergleichendes Zitat.\footnote{\cite[vgl.][5\psqq]{Maslennikov2011}}
```
ist gleich folgendem Kommando:

```latex
Ein vergleichendes Zitat.\footcite[vgl.][5\psqq]{Maslennikov2011}
```

**Comment by thunermay** [comment]
Ja genau richtig. Kann/Soll man dafür einen Pull-Request erstellen?

**Comment by mfueller** [comment]
Ja, gerne per PR

**Comment by mfueller** [comment]
closed by PR #17
