### ISSUE TITLE
Glossary outputs a blank page

### ISSUE THREAD

**Issue by aublue** [FHDWPB/latex-thesis-template#5]
Hi,

the current template outputs a blank page for the glossary. 
![grafik](https://user-images.githubusercontent.com/48840989/78507158-b4230500-777e-11ea-82d7-4c43bf44f7eb.png)

Comparison current version (GitHub), current version (generated on my pc):
![grafik](https://user-images.githubusercontent.com/48840989/78507218-1ed44080-777f-11ea-8d54-211cae38aeb9.png)

latex/pdflatex version:
![grafik](https://user-images.githubusercontent.com/48840989/78507264-65c23600-777f-11ea-8bd2-2c3d32c9b977.png)

os version:
![grafik](https://user-images.githubusercontent.com/48840989/78507251-5511c000-777f-11ea-940a-0fe961f7c5d9.png)

How can I fix this issue?

Best regards 
aublue

**Comment by jlnprssnr** [comment]
See chapter 2.6 for the full build script. Just 1x pdflatex Thesis is not sufficient.

**Comment by aublue** [comment]
Thank you very much - this was a typical layer 8 issue on my side. 

Offtopic: Is there an option to add a layer below subsubsection that will show up in the table of content? I would like to add at least two more layers to my document.

**Comment by jlnprssnr** [comment]
That is indeed rather offtopic and a) something you can type into Google and b) something you should discuss with your supervisor
But considering the nature of TeX, the answer to almost any question - within reason - is yes.
